project:
  type: website
  render:
    - "*.qmd"
    - "*.py"
    - "!guides/"
    - "!examples/"
  output-dir: ../docs
  execute-dir: project

toc: true

website:
  title: "Kaggle Benchmarks"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: quick_start.qmd
      - href: user_guide.qmd
      - href: cookbook.qmd


format:
  html:
    # theme: darkly
    theme: yeti
    css: styles.css
    toc: true
    page-layout: full

execute:
  cache: true
